### ISSUE TITLE
Micro version is not being updated

### ISSUE THREAD

**Issue by doggy-dev** [cbrun/baseliner#1]
Hello,

thanks for the nice plugin. I'll definitely give it a try in production. However I noticed that micro version of the bundles is not being bumped. Is this feature left out on purpose or is it just not implemented yet?

**Comment by cbrun** [comment]
It was actually a bug which I fixed a few days ago.
You should try again ;)

I also introduced the capability to "provision" an API baseline just from a .target file. This is kinda hidden for now as there is no UI, but you can have a look on how I enabled it in a given project : https://git.eclipse.org/r/#/c/40644/
