### ISSUE TITLE
The baseliner seems to change the workspace opened by Eclipse

### ISSUE THREAD

**Issue by sbegaudeau** [cbrun/baseliner#3]
Since I have installed the baseliner, my Eclipse opens with the default workspace location (/Users/username/Documents/workspace on Mac OS) without asking me anything. My Eclipse is configured to ask me which workspace I want to use when it starts and I never use the default workspace on this Eclipse.

**Comment by sbegaudeau** [comment]
This may be related to this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=409552

**Comment by sbegaudeau** [comment]
More specifically: https://bugs.eclipse.org/bugs/show_bug.cgi?id=409552#c25

Was able to identified the cause of why the org.eclipse.jdt.apt.core 
plugin being activated too early in our product Konstantin mentioned above:

In our server adapter plugin, there is an explicit(but unnecessary) 
call of Bundle.start() to start org.eclipse.jdt.apt.core plugin.

Bundle.start() is equivalent to Bundle.start(0), which 
change of the status of the jdt.apt.core plugin, clearing the bundle's
BUNDLE_ACTIVATION_POLICY bit, which is supposed to be lazyload. 
The status is then persisted after IDE is shutdown. 

When IDE is restarted, the platform will eager load the jdt.apt.core plugin, 
in turn triggers org.eclipse.core.resource plugin, setting the IDE 
workspace location, causing the subsequent platform UI prompt 
of workspace dialog being skipped.  

After remove the Bundle.start(), problem is fixed.

**Comment by cbrun** [comment]
Thanks for the input !

Digging further and debugging (thanks to  : https://bugs.eclipse.org/bugs/show_bug.cgi?id=409552#c13) 

Looks like fr.obeo.baseliner.pde.PDEBaselineJarProvider is causing the early instanciation.

**Comment by cbrun** [comment]
Please note that once you installed the build containing the fix, you need to start your Eclipse with -clean at least once to force the re-wiring of the bundles.
